[package]
name = "judge"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
rusqlite = { version = "0.34.0", features = ["bundled"] }
serenity = "0.12.4"
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
